// ===========================================================================
// @file GermaniumParamMap.hpp
// @brief Shared register/field/command definitions for ZynqDetector & ADGermanium
// @author Auto-generated by Copilot, 2026-04-10
// ===========================================================================
#pragma once

#include <cstdint>

// ------------------- Register Offsets -------------------
namespace GermaniumReg {
static constexpr uint16_t MARS_CONF_LOAD    = 0;
static constexpr uint16_t LEDS              = 1;
static constexpr uint16_t MARS_CONFIG       = 2;
static constexpr uint16_t VERSIONREG        = 3;
static constexpr uint16_t MARS_CALPULSE     = 4;
static constexpr uint16_t MARS_PIPE_DELAY   = 5;
static constexpr uint16_t DETECTOR_TYPE     = 6;
static constexpr uint16_t MARS_RDOUT_ENB    = 8;
static constexpr uint16_t EVENT_TIME_CNTR   = 9;
static constexpr uint16_t SIM_EVT_SEL       = 10;
static constexpr uint16_t SIM_EVENT_RATE    = 11;
static constexpr uint16_t ADC_SPI           = 12;
static constexpr uint16_t CALPULSE_CNT      = 16;
static constexpr uint16_t CALPULSE_RATE     = 17;
static constexpr uint16_t CALPULSE_WIDTH    = 18;
static constexpr uint16_t CALPULSE_MODE     = 19;
static constexpr uint16_t TD_CAL            = 20;
static constexpr uint16_t EVENT_FIFO_DATA   = 24;
static constexpr uint16_t EVENT_FIFO_CNT    = 25;
static constexpr uint16_t EVENT_FIFO_CTRL   = 26;
static constexpr uint16_t UDP_IP_ADDR       = 40;
static constexpr uint16_t TRIG              = 52;
static constexpr uint16_t COUNT_TIME_LO     = 53;
static constexpr uint16_t COUNT_TIME_HI     = 54;
static constexpr uint16_t FRAME_NO          = 55;
static constexpr uint16_t COUNT_MODE        = 56;
}


// ------------------- Global Field IDs -------------------
enum MarsGlobalField {
    MARS_FIELD_ST   = 0,
    MARS_FIELD_GAIN = 1,
    MARS_FIELD_POL  = 2,
    MARS_FIELD_EBLK = 3,
    MARS_FIELD_GMON = 4,
    MARS_FIELD_PUEN = 5,
    MARS_FIELD_MFS  = 6,
    MARS_FIELD_TDS  = 7,
    MARS_FIELD_TDM  = 8,
    MARS_FIELD_TH   = 9,
    MARS_FIELD_C    = 10,
    MARS_FIELD_M0   = 11,
    MARS_FIELD_SAUX = 12,
};

// ------------------- Channel Field IDs -------------------
enum MarsChannelField {
    MARS_CH_CHEN = 0,
    MARS_CH_TSEN = 1,
    MARS_CH_THTR = 2,
    MARS_CH_PUTR = 3,
};
