// ===========================================================================
// @file GermaniumParamMap.hpp
// @brief Shared register/field/command definitions for ZynqDetector & ADGermanium
// @author Auto-generated by Copilot, 2026-04-10
// ===========================================================================
#pragma once

#include <cstdint>

#include "GermaniumDetectorProtocol.hpp"

// ------------------- Register Offsets -------------------
namespace GermaniumReg {
using GermaniumProtocol::Register::MARS_CONF_LOAD;
using GermaniumProtocol::Register::LEDS;
using GermaniumProtocol::Register::MARS_CONFIG;
using GermaniumProtocol::Register::VERSIONREG;
using GermaniumProtocol::Register::MARS_CALPULSE;
using GermaniumProtocol::Register::MARS_PIPE_DELAY;
using GermaniumProtocol::Register::DETECTOR_MODEL;
using GermaniumProtocol::Register::MARS_RDOUT_ENB;
using GermaniumProtocol::Register::EVENT_TIME_CNTR;
using GermaniumProtocol::Register::SIM_EVT_SEL;
using GermaniumProtocol::Register::SIM_EVENT_RATE;
using GermaniumProtocol::Register::ADC_SPI;
using GermaniumProtocol::Register::CALPULSE_CNT;
using GermaniumProtocol::Register::CALPULSE_RATE;
using GermaniumProtocol::Register::CALPULSE_WIDTH;
using GermaniumProtocol::Register::CALPULSE_MODE;
using GermaniumProtocol::Register::TD_CAL;
using GermaniumProtocol::Register::EVENT_FIFO_DATA;
using GermaniumProtocol::Register::EVENT_FIFO_CNT;
using GermaniumProtocol::Register::EVENT_FIFO_CTRL;
using GermaniumProtocol::Register::UDP_IP_ADDR;
using GermaniumProtocol::Register::TRIG;
using GermaniumProtocol::Register::COUNT_TIME_LO;
using GermaniumProtocol::Register::COUNT_TIME_HI;
using GermaniumProtocol::Register::FRAME_NO;
using GermaniumProtocol::Register::COUNT_MODE;
}

// ------------------- Global Field IDs -------------------
enum MarsGlobalField {
    MARS_FIELD_ST   = 0,
    MARS_FIELD_GAIN = 1,
    MARS_FIELD_POL  = 2,
    MARS_FIELD_EBLK = 3,
    MARS_FIELD_GMON = 4,
    MARS_FIELD_PUEN = 5,
    MARS_FIELD_MFS  = 6,
    MARS_FIELD_TDS  = 7,
    MARS_FIELD_TDM  = 8,
    MARS_FIELD_TH   = 9,
    MARS_FIELD_C    = 10,
    MARS_FIELD_M0   = 11,
    MARS_FIELD_SAUX = 12,
};

// ------------------- Channel Field IDs -------------------
enum MarsChannelField {
    MARS_CH_CHEN = 0,
    MARS_CH_TSEN = 1,
    MARS_CH_THTR = 2,
    MARS_CH_PUTR = 3,
};
